config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: 'application#index'

  resources :users, only: [:create, :show, :edit, :update, :index]
  resources :eventos_academicos, only: [:index]

  resources :eventos_culturais, only: [:index]

  resources :inscricoes, only: [:index, :new, :show]

  match '/contatos', to: 'contatos#new', via: 'get'
  resources :contatos, only: [:new, :create]

  resources :mostras_cientifica, only: [:index]

  resources :cronogramas, only: [:index]

  resources :infraestruturas, only: [:index]

  resources :pacotes, only: [:index]

  resources :checkouts, only: [:create]
  resources :notifications, only: [:create]

  namespace :admin do
    resources :inscricoes
  end

  get '/edital' => 'mostras_cientifica#download_edital', as: :download_edital
  get '/formulario' => 'mostras_cientifica#download_formulario', as: :download_formulario
  get '/resumo_extendido' => 'mostras_cientifica#download_resumo_extendido', as: :download_resumo_extendido
  get '/modelo_banner' => 'mostras_cientifica#download_modelo_banner', as: :download_modelo_banner
  get '/artigos_selecionados' => 'mostras_cientifica#download_artigos_selecionados', as: :download_artigos_selecionados
  get '/download_errata_edital' => 'mostras_cientifica#download_errata_edital', as: :download_errata_edital

  scope 'admin' do
    resource :dashboards, only: [:show], path: ''
    resources :eventos_academicos, only: [:new, :create, :update, :destroy]
    resources :eventos_culturais, only: [:new, :create, :update, :destroy]
  end

end

app/controllers/admin/inscricoes_controller.rb
class Admin::InscricoesController < ApplicationController

  def new
    raise PermissionDenied unless current_user.admin
    render 'admin/inscricoes/new.html.erb'
  end

  def create
    begin
      InscricaoManager.create_for_admin(params['user'].permit!, params['inscricao'].permit!)
      redirect_to inscricoes_path
    rescue InscricaoError => e
      flash['error'] = e.message
      redirect_to new_admin_inscricao_path
    rescue => e
      flash['error'] = e.message
      redirect_to new_admin_inscricao_path
    end
  end

end

app/controllers/inscricoes_controller.rb
class InscricoesController < ApplicationController
  before_filter :require_login

  def index
    raise PermissionDenied unless current_user.admin
    @q = Inscricao.ransack(params[:q])
    @inscricoes = @q.result(distinct: true).where.not(status: nil).page(params[:page]).per(20)

    respond_to do |format|
      format.html
      format.json { render json: @inscricoes }
    end
  end

  def new
    @inscricao = Inscricao.new
  end

  def show
    @inscricao = Inscricao.find_by(user_id = current_user.id)
  end

  def create
    begin
      flash[:success] = 'Parabéns! VocÊ foi inscrito no coneeagri UFF 2016'
    rescue
      render 'new'
    end
  end

  private

  def options
    {
      query: params[:q],
      page: params[:p],
      per_page: params[:per_page] || 20
    }
  end
end

app/views/admin/inscricoes/new.html.erb
<div class="container">
  <h1>Cadastrar inscrição</h1>

  <div class="divider"></div>

  <% if flash[:error] %>
    <div style="background-color: #e57373; margin-bottom: 10px; border: 1px solid #b71c1c; text-align: center">
      <p id="flash_error">
        <%= flash[:error] %>
      </p>
    </div>
  <% end %>

  <%= form_tag(admin_inscricoes_path, :method=>'post') do %>
    <div class="row">
      <div class="input-field col s8">
        <input id="user_name" type="text" name="user[name]" >
        <label for="user_name">Nome</label>
      </div>

      <div class="input-field col s4">
        <select name="user[sexo]">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="M">Masculino</option>
          <option value="F">Feminino</option>
        </select>
        <label>Sexo</label>
      </div>

      <div class="input-field col s6">
        <input id="user_email" type="text" name="user[email]" >
        <label for="user_email">Email</label>
      </div>

      <div class="input-field col s6">
        <input id="user_university" type="text" name="user[university]" >
        <label for="user_university">Universidade</label>
      </div>

      <div class="input-field col s6">
        <input id="user_cpf" type="text" name="user[cpf]" >
        <label for="user_cpf">CPF</label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <select name="inscricao[pacote]" id="inscricao_inscricao_pacote">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="4">Pacote Completo</option>
          <option value="5">Pacote sem Alojamento</option>
          <option value="6">Pacote Acadêmico</option>
        </select>
        <label>Pacote</label>
      </div>

      <div class="input-field col s6">
        <select name="inscricao[visita_tecnica]" id="inscricao_visita_tecnica">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value='3'>Visita 3 - Embrapa Solos (Jardim Botânico RJ)</option>
        </select>
        <label>Visita técnica</label>
      </div>

      <div class="input-field col s6">
        <select name="inscricao[minicurso_1]" id="inscricao_minicurso_1">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="1">Minicurso 1 - Técnicas de irrigação para gramados esportivos (Rain Bird)</option>
          <option value="2">Minicurso 2 - Saneamento e Drenagem Urbana</option>
          <option value="3">Minicurso 3 - Modelagem Fuzzi em Biossitema Animal</option>
          <option value="4">Minicurso 4 - Currículo como Ferramenta de Desenvolvimento Pessoal e Competitividade no Mercado
          </option>
        </select>
        <label>Minicurso 1</label>
      </div>

      <div class="input-field col s6">
        <select name="inscricao[minicurso_2]" id="inscricao_minicurso_2">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="1">Minicurso 1 - Técnicas de irrigação para gramados esportivos (Rain Bird)</option>
          <option value="2">Minicurso 2 - Saneamento e Drenagem Urbana</option>
          <option value="3">Minicurso 3 - Modelagem Fuzzi em Biossitema Animal</option>
          <option value="4">Minicurso 4 - Currículo como Ferramenta de Desenvolvimento Pessoal e Competitividade no Mercado
          </option>
        </select>
        <label>Minicurso 2</label>
      </div>

      <div class="input-field col s6">
        <select name="inscricao[tamanho_camisa]" id="inscricao_tamanho_camisa">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="P">Pequena</option>
          <option value="M">Média</option>
          <option value="G">Grande</option>
          <option value="GG">Extra Grande</option>
        </select>
        <label>Tamanho da camisa</label>
      </div>

      <div class="input-field col s6">
        <select name="inscricao[status]" id="inscricao_status">
          <option value="" disabled selected>Escolha uma opção</option>
          <option value="20">Aguardando Pagamento</option>
          <option value="30">Paga</option>
        </select>
        <label>Status da Inscrição</label>
      </div>
    </div>

    <div class="right-align">
    <%= submit_tag 'Cadastrar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('select').material_select();
  });
</script>