config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: 'application#index'

  resources :users, only: [:create, :show, :edit, :update, :index]
  resources :eventos_academicos, only: [:index]

  resources :eventos_culturais, only: [:index]

  resources :inscricoes, only: [:index, :new, :show]

  match '/contatos', to: 'contatos#new', via: 'get'
  resources :contatos, only: [:new, :create]

  resources :mostras_cientifica, only: [:index]

  resources :cronogramas, only: [:index]

  resources :infraestruturas, only: [:index]

  resources :pacotes, only: [:index]

  resources :checkouts, only: [:create]
  resources :notifications, only: [:create]

  namespace :admin do
    resources :inscricoes
  end

  get '/edital' => 'mostras_cientifica#download_edital', as: :download_edital
  get '/formulario' => 'mostras_cientifica#download_formulario', as: :download_formulario
  get '/resumo_extendido' => 'mostras_cientifica#download_resumo_extendido', as: :download_resumo_extendido
  get '/modelo_banner' => 'mostras_cientifica#download_modelo_banner', as: :download_modelo_banner
  get '/artigos_selecionados' => 'mostras_cientifica#download_artigos_selecionados', as: :download_artigos_selecionados
  get '/download_errata_edital' => 'mostras_cientifica#download_errata_edital', as: :download_errata_edital

  scope 'admin' do
    resource :dashboards, only: [:show], path: ''
    resources :eventos_academicos, only: [:new, :create, :update, :destroy]
    resources :eventos_culturais, only: [:new, :create, :update, :destroy]
  end

end

app/controllers/mostras_cientifica_controller.rb
class MostrasCientificaController < ApplicationController

  def index
  end

  def download_edital
    send_file(
        "#{Rails.root}/public/IC-base-do-edital-novo.pdf",
        :disposition => 'inline',
        filename: "Edital.pdf",
        type: "application/pdf",
        :x_sendfile => true
    )
  end

  def download_formulario
    send_file(
        "#{Rails.root}/public/Formulário de Inscrição para Mostra de Iniciação Científica do Coneeagri 2016.docx",
        filename: "Formulário de Inscrição para Mostra de Iniciação Científica do Coneeagri 2016.docx",
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
  end

  def download_resumo_extendido
    send_file(
        "#{Rails.root}/public/resumo-extendido-modelo.pdf",
        :disposition => 'inline',
        filename: "Resumo do Modelo.pdf",
        type: "application/pdf",
        :x_sendfile => true
    )
  end

  def download_modelo_banner
    send_file(
      "#{Rails.root}/public/modelo-de-banner.pdf",
      :disposition => 'inline',
      filename: "Modelo de Banner.pdf",
      type: "application/pdf",
      :x_sendfile => true
    )
  end

  def download_artigos_selecionados
    send_file(
      "#{Rails.root}/public/artigos-selecionados.pdf",
      :disposition => 'inline',
      filename: "Artigos Selecionados.pdf",
      type: "application/pdf",
      :x_sendfile => true
    )
  end

  def download_errata_edital
    send_file(
      "#{Rails.root}/public/errata01-datas-artigos.pdf",
      :disposition => 'inline',
      filename: "Errata 01 - Datas dos Artigos.pdf",
      type: "application/pdf",
      :x_sendfile => true
    )
  end

end

app/views/mostras_cientifica/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h1>Mostra Científica</h1>
    </div>
  </div>
  <div class="divider"></div>

  <div class="row">
    <div class="col s12">
      <span style="font-size: 18px"><strong><%= link_to 'Download - Artigos Selecionados', download_artigos_selecionados_path, :target => "_blank" %></strong></span>

      <p>Faça o download do PDF com os artigos que foram selecionados</p>
    </div>
  </div>

  <div class="row">
      <div class="col s12">
        <span style="font-size: 18px"><strong><%= link_to 'Download - Edital', download_edital_path, :target => "_blank" %></strong></span>

        <p>Faça o download do edital</p>
      </div>
  </div>
  <div class="row">
      <div class="col s12">
        <span style="font-size: 18px"><strong><%= link_to 'Download - Formulário', download_formulario_path %></strong></span>

        <p>Submissão de artigos até o dia 04/12.
          Faça o download do formulário e envie o preenchido para o email <strong style="color: #1b5e20"> academico@coneeagri.com.br</strong></p>
      </div>
  </div>
  <div class="row">
    <div class="col s12">
      <span style="font-size: 18px"><strong><%= link_to 'Download - Modelo do Resumo', download_resumo_extendido_path, :target => "_blank" %></strong></span>

      <p>Faça o download do modelo do resumo do formato de trabalho</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <span style="font-size: 18px"><strong><%= link_to 'Download - Modelo de banner', download_modelo_banner_path, :target => "_blank" %></strong></span>

      <p>Faça o download do modelo de Banner</p>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <span style="font-size: 18px"><strong><%= link_to 'Download - Errata do Edital', download_errata_edital_path, :target => "_blank" %></strong></span>

      <p>Faça o download da errata do edital</p>
    </div>
  </div>

</div>