config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  root to: 'application#index'

  resources :users, only: [:create, :show, :edit, :update, :index]
  resources :eventos_academicos, only: [:index]

  resources :eventos_culturais, only: [:index]

  resources :inscricoes, only: [:index, :new, :show]

  match '/contatos', to: 'contatos#new', via: 'get'
  resources :contatos, only: [:new, :create]

  resources :mostras_cientifica, only: [:index]

  resources :cronogramas, only: [:index]

  resources :infraestruturas, only: [:index]

  resources :pacotes, only: [:index]

  resources :checkouts, only: [:create]
  resources :notifications, only: [:create]

  namespace :admin do
    resources :inscricoes
  end

  get '/edital' => 'mostras_cientifica#download_edital', as: :download_edital
  get '/formulario' => 'mostras_cientifica#download_formulario', as: :download_formulario
  get '/resumo_extendido' => 'mostras_cientifica#download_resumo_extendido', as: :download_resumo_extendido
  get '/modelo_banner' => 'mostras_cientifica#download_modelo_banner', as: :download_modelo_banner
  get '/artigos_selecionados' => 'mostras_cientifica#download_artigos_selecionados', as: :download_artigos_selecionados
  get '/download_errata_edital' => 'mostras_cientifica#download_errata_edital', as: :download_errata_edital

  scope 'admin' do
    resource :dashboards, only: [:show], path: ''
    resources :eventos_academicos, only: [:new, :create, :update, :destroy]
    resources :eventos_culturais, only: [:new, :create, :update, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>CONEEAGRI UFF 2016</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
    <header>
      <ul id="event-dropdown" class="dropdown-content">
        <li><%= link_to 'Culturais', eventos_culturais_path %></li>
        <li><%= link_to 'Acadêmicos', eventos_academicos_index_path %></li>
      </ul>
      <ul id="congress-dropdown" class="dropdown-content">
        <li><%= link_to 'Mostra Científica', mostras_cientifica_path %></li>
        <li><%= link_to 'Infraestrutura', infraestruturas_path %></li>
        <li><%= link_to 'Cronograma', cronogramas_path %></li>
      </ul>
        <nav role="navigation">
          <div class="nav-wrapper container">
            <%=link_to( image_tag('logo_menor.png'), root_path, :class=>"brand-logo") %>
            <ul id="slide-out" class="side-nav">
              <li>
                <a class="dropdown-button" href="#!" data-activates="congress-dropdown">Informações<i class="material-icons right">arrow_drop_down</i></a>
              </li>
              <li>
                <a class="dropdown-button" href="#!" data-activates="event-dropdown">Eventos<i class="material-icons right">arrow_drop_down</i></a>
              </li>
              <li><%= link_to 'Pacotes', pacotes_path %></li>
              <% unless current_user %>
                <%= react_component('LoginHeader', {}) %>
                <li><%= link_to 'Contato', new_contato_path %></li>
              <% else %>
                <ul id="user-dropdown" class="dropdown-content">
                  <% if current_user.admin? %>
                    <li><%= link_to 'Cadastros', users_path %></li>
                    <li><%= link_to 'Inscrições', inscricoes_path %></li>
                  <% else %>
                    <li><%= link_to 'Minhas inscrições', inscricao_path(current_user.id) %></li>
                  <% end %>
                  <li><%= link_to 'Contato', new_contato_path %></li>
                  <li><%= link_to 'Minha Conta', user_path(current_user.id) %></li>
                  <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                </ul>
                <li>
                  <a class="dropdown-button" href="#!" data-activates="user-dropdown">
                    <%= "#{current_user.name}" %>
                    <i class="material-icons right">account_circle</i>
                  </a>
                </li>
              <% end %>
              <li><%= link_to 'Contato', new_contato_path %></li>
            </ul>
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>
                <a class="dropdown-button" href="#!" data-activates="congress-dropdown">Informações<i class="material-icons right">arrow_drop_down</i></a>
              </li>
              <li>
                <a class="dropdown-button" href="#!" data-activates="event-dropdown">Eventos<i class="material-icons right">arrow_drop_down</i></a>
              </li>
              <li><%= link_to 'Pacotes', pacotes_path %></li>
              <% unless current_user %>
                <li><%= react_component('LoginHeader', {}) %></li>
                <li><%= link_to 'Contato', new_contato_path %></li>
              <% else %>
                <ul id="user-dropdown" class="dropdown-content">
                  <% if current_user.admin? %>
                    <li><%= link_to 'Cadastros', users_path %></li>
                    <li><%= link_to 'Inscrições', inscricoes_path %></li>
                  <% else %>
                    <li><%= link_to 'Minhas inscrições', inscricao_path(current_user.id) %></li>
                  <% end %>
                  <li><%= link_to 'Contato', new_contato_path %></li>
                  <li><%= link_to 'Minha Conta', user_path(current_user.id) %></li>
                  <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                </ul>
                <li>
                  <a class="dropdown-button" href="#!" data-activates="user-dropdown">
                    <%= "#{current_user.name}" %>
                    <i class="material-icons right">account_circle</i>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
    </header>

    <main>
      <%= react_component('RegisterModal', {}) %>
      <%= yield %>
    </main>

<footer class="page-footer">
  <div class="container">
    <p>

      Coneeagri UFF 2016 |
      Todos os direitos reservados

    </p>
  </div>
</footer>
</body>
</html>